# Generated by Django 5.0.6 on 2024-05-21 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beebot', '0002_botuser_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmessage',
            name='keyword',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
