# Generated by Django 5.0.6 on 2024-05-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beebot', '0003_botmessage_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botbuttons',
            name='text',
            field=models.CharField(max_length=50, verbose_name='Текст кнопки на Русском'),
        ),
        migrations.AlterField(
            model_name='botbuttons',
            name='text_eng',
            field=models.CharField(max_length=50, verbose_name='Текст кнопки на Кыргызском'),
        ),
        migrations.AlterField(
            model_name='botmessage',
            name='message',
            field=models.TextField(verbose_name='Сообщение бота на Русском'),
        ),
        migrations.AlterField(
            model_name='botmessage',
            name='message_eng',
            field=models.TextField(verbose_name='Соощение бота на Кыргызском'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='language',
            field=models.CharField(choices=[('rus', 'Russian'), ('kg', 'Kyrgyz')], max_length=10, verbose_name='Язык'),
        ),
    ]
