# Generated by Django 5.0.6 on 2024-05-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beebot', '0004_alter_botbuttons_text_alter_botbuttons_text_eng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottoken',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name='Название Бота'),
            preserve_default=False,
        ),
    ]
